#coding=utf-8

FACEBOOK_ACCOUNT1=""
FACEBOOK_ACCOUNT1_PWD=""
FACEBOOK_ACCOUNT1_DISPLAYNAME=u"測試機"
FACEBOOK_ACCOUNT1_SOOCIIID=""

EMAIL_ACCOUNT=""
EMAIL_PWD=""
EMAIL_NAME=""

TWITTER_ACCOUNT=""
TWITTER_ACCOUNT_PWD=""
